# Generated by Django 3.2 on 2021-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default='0', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='products',
            name='published',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_categories',
            field=models.ManyToManyField(related_name='Categories', to='myapi.Category'),
        ),
    ]
